[package]
name = "esp-idf-ableton-link"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Safe Rust wrapper for Ableton Link on ESP32 via ESP-IDF"
keywords = ["esp32", "esp-idf", "ableton", "link", "music"]
categories = ["embedded", "hardware-support"]

[dependencies]
esp-idf-sys = "0.36"
log = "0.4"

[features]
default = []
std = []

[build-dependencies]
glob = "0.3"

[package.metadata.esp-idf-sys]
extra_components = [
    { component_dirs = ["../esp-idf-ableton-link"], bindings_header = "../esp-idf-ableton-link/ableton-link/extensions/abl_link/include/abl_link.h", bindings_module = "ableton_link" },
    { remote_component = { name = "espressif/asio", version = "*" } }
]
